# NumPy

In [1]:
import numpy as np

In [2]:
python_lista = [1, 2, 3, 4, 5]
numpy_ndarray = np.array([1, 2, 3, 4, 5])

print(f'Mnozenje Python liste {python_lista * 2}')
print(f'Mnozenje NumPy ndArray {numpy_ndarray * 2}')

Mnozenje Python liste [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Mnozenje NumPy ndArray [ 2  4  6  8 10]


In [6]:
# [element * 2 for element in python_lista]
# ili
np.multiply(python_lista, 2)

array([ 2,  4,  6,  8, 10])

In [7]:
python_lista = []
np.multiply(python_lista, 2)

array([], dtype=float64)

In [9]:
podaci = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(podaci)

np_podaci = np.array(podaci)
print(np_podaci)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
np_podaci.size

9

In [11]:
np_podaci.ndim

2

In [12]:
podaci = [[1, 2, 3], [4, 5, 6], [7, 8]]
print(podaci)

np_podaci = np.array(podaci)
print(np_podaci)

[[1, 2, 3], [4, 5, 6], [7, 8]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [13]:
lista = [
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]],
    [[17, 18 ,19, 20], [21, 22, 23, 24], [25, 26, 27, 28], [29, 30, 31, 32]],
    [[33, 34, 35, 36], [37, 38, 39, 40], [41, 42, 43, 44], [45, 46, 47, 48]]
]

np_lista = np.array(lista)
np_lista

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [14]:
np_lista.ndim

3

In [15]:
np_lista.size

48

In [16]:
np_lista.shape

(3, 4, 4)

In [17]:
np_podaci.shape

(3, 3)

In [25]:
print('bytes', np_lista.nbytes)
print('item size', np_lista.itemsize)
print('size', np_lista.size)
print('dtype', np_lista.dtype)
print()
print('bytes', np_podaci.nbytes)
print('item size', np_podaci.itemsize)
print('size', np_podaci.size)
print('dtype', np_podaci.dtype)

bytes 384
item size 8
size 48
dtype int64

bytes 72
item size 8
size 9
dtype int64


In [26]:
np_lista = np.array(np_lista, dtype=np.int16)

print('bytes', np_lista.nbytes)
print('item size', np_lista.itemsize)
print('size', np_lista.size)
print('dtype', np_lista.dtype)

bytes 96
item size 2
size 48
dtype int16


In [27]:
np_lista = np.array(np_lista, dtype=np.float64)
np_lista

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]],

       [[17., 18., 19., 20.],
        [21., 22., 23., 24.],
        [25., 26., 27., 28.],
        [29., 30., 31., 32.]],

       [[33., 34., 35., 36.],
        [37., 38., 39., 40.],
        [41., 42., 43., 44.],
        [45., 46., 47., 48.]]])

In [28]:
print('bytes', np_lista.nbytes)
print('item size', np_lista.itemsize)
print('size', np_lista.size)
print('dtype', np_lista.dtype)

bytes 384
item size 8
size 48
dtype float64
