# Uvod u NumPy

Prije nego krenemo raditi s bibliotekom NumPy, objasnit ćemo na široj slici što je zapravo NumPy biblioteka. Do sad smo se fokusirali na dvije biblioteke, a to su bile Pandas i Matplotlib. Za Pandas smo već spomenuli kako je napravljen na temeljima NumPy-a. To znači da biblioteka Pandas i sama koristi NumPy biblioteku kao osnovu. To smo mogli primjetiti tako što su tipovi podataka koje Pandas koristi zapravo tipovi podataka iz biblioteke NumPy.

Matplotlib je biblioteka za vizualizaciju. Zanimljivo je da i ona kao svoju osnovu koristi biblioteku NumPy.

Možemo zaključiti kako je NumPy biblioteka fundamentalna biblioteka nad kojom se mogu raditi moćni alati. Ali još nismo odgovorili što zapravo NumPy je.

NumPy je biblioteka koja je napisana u programskom jeziku C i visoko je optimizirana. Što znači da operacije nad podacima može obavljati veoma brzo - brže nego što to može Python sa svojim tipovima podataka. Kako bi pristupili performansama jezika C, NumPy je zaokrušio (wrapper) biblioteku koja je napisana u programskoj jeziku C i pruža Python sučelje, što znači da biblioteku koristimo kao i svaku drugu.

NumPy je *open-source* biblioteka namijenjena za kompleksne matematičke proračune. Nudi jako puno matematičkih funkcija, generator je nasumičnih brojeva, podrška je za proračune vezane uz linearnu algebru, Fourierove transformacije. Mi ćemo ga koristiti za obradu višedimenzionalnih nizova i matrica.

Na službenoj stranici NumPy biblioteke možete pronaći dokumentaciju, preuzeti i instalirati NumPy, pronaći neke tečajeve, pridružiti se zajednici korisnika. Poveznica na stranicu je: https://numpy.org/.

## ndarray tip podatka - temelj NumPy biblioteke

Temelj NumPy biblioteke je *ndarray* objekt. Naziv dolazi od *n-dimensional array*, odnosno višedimenzionalni niz. Prije nego pojasnimo što su višedimenzionalni nizovi, dobro bi bilo objasniti što je to niz, odnosno *array*. *Array* je tip podatka koji je najsličniji Python listi. Nije isti jer postoje razlike, ne samo u načinu kako je niz programiran za rad s podacima (što je tema za kolegije na fakultetima), nego i nekoliko je nama "vidljivih" razlika. *Array* (mi ćemo dalje u tekstu ponekad koristiti i naziv *Array*):
- je kolekcija elemenata istog tipa podataka
- podržava izravne matematičke operacije nad elementima (*array* * 2 - množi svaki element niza s brojem dva)
- nije zamišljen za mijenjanje elemenata. Podržava ih, ali je daleko manje učinkovit od liste.

Najbolje je napraviti nekoliko primjera pa će zasigurno biti jasnije.

Kao i uvijek do sada, prvo moramo napraviti *import* NumPy biblioteke kako bismo kasnije mogli koristiti dostupne mogućnosti.

Preporuka je koristiti način uključivanja biblioteke koji je gotovo postao standard. Uporaba drugačijeg načina neće utjecati na funkcionalnost programa, ali neće biti u skladu s najboljim praksama.

Nakon toga pokazati ćemo koja je jedna od razlika Python liste i ndarray tipa podataka. 

In [116]:
import numpy as np

python_lista = [1, 2, 3, 4, 5]
numpy_ndarray = np.array([1, 2, 3, 4, 5])

# Semantika množenja je drugačija!
# NumPy se slaže s definicijama u matematici.
print(f'Mnozenje Python Liste: {python_lista * 2}')
print(f'Mnozenje NumPy ndArray: {numpy_ndarray * 2}')

Mnozenje Python Liste: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Mnozenje NumPy ndArray: [ 2  4  6  8 10]


Ako već imamo Python listu, NumPy pruža mogućnost da dobijemo isto ponašanje.

In [117]:
np.multiply(python_lista, 2)

array([ 2,  4,  6,  8, 10])

1. Vježba

Možete li konstruirati `python_lista` na način da neće moći biti moguće dobiti rezultat množenja liste s 2?

In [118]:
python_lista = [] # TODO
np.multiply(python_lista, 2)

array([], dtype=float64)

### *ndarray size* - broj elemenata u *Array* objektu

Svojstvo *size* vraća ukupan broj elemenata u objektu. Pokažimo to na primjeru.

In [119]:
podaci = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(podaci)
np_podaci = np.array(podaci)
print(np_podaci)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Uočite kako je ispis podataka drugačiji.

Provjerimo koliko elemenata ima novokreirani *Array* objekt:

In [120]:
np_podaci.size

9

Vidjeli smo kako je ispis za *Array* drugačiji od obične Python liste. Svaku listu je prikazao u novom redu. Na ovaj način smo dobili 3x3 matricu.

Ako zamislimo da je NumPy *Array* u koordinatnom sustavu, svaki od redova bit će na X osima, svaka kolona će biti na Y osi. Ovaj podatak zovemo dimenzije, odnosno osi ili engleski *axis*. Jako često ćemo trebati informaciju koliko dimenzija ima naš *Array* objekt. Za to koristimo svojstvo ***ndim***. Provjerimo koliko naš *Array* objekt ima osi:

In [121]:
np_podaci.ndim

2

Očekivano, dvije osi. Kako izgleda *Array* s tri osi?

In [122]:
lista = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], 
         [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
         [[25, 26, 27, 28], [29, 30, 31, 32] ,[33, 34, 35, 36]]]
tri_d = np.array(lista)
tri_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [123]:
tri_d.ndim

3

Dakle, treću dimenziju ćemo dobiti ukoliko *Array* kreiramo od liste, koja kao elemente ima listu, koja opet kao elemente ima listu.

A kakvog je oblika naš *Array*? Ako koristimo svojstvo *Shape*, dobit ćemo *tuple* s brojem redova i stupaca koje imamo, ali po svakoj dimenziji. Najbolje je to pokazati na primjeru kako bi vam bilo jasnije.

In [124]:
np_podaci.shape

(3, 3)

Vidimo da se naš *Array np_podaci* sastoji od dvije dimenzije (imamo samo dva podatka u *tupleu*) u kojima imamo tri reda i tri stupca. Provjerimo kakvog je oblika *Array tri_d*:

In [125]:
tri_d.shape

(3, 3, 4)

Sada smo dobili tri podatka pa je zaključak kako imamo **tri** dimenzije i u svakoj od dimenzija imamo **tri reda** i **četiri stupca**.

Već smo rekli kako u *Array* možemo pohraniti podatke **istog tipa**, ali to ne znači da ti podaci moraju biti isključivo cijeli brojevi. Osim toga, *Array* je namijenjen za rad s velikom količinom podatka pa je podataka o tipu i količini memorije koju taj tip zauzima jako koristan. Provjerimo koji je tip (*dtype*) u našim *Array* objektima te koliko memorije oni zauzimaju pojedinačno (*itemsize*), odnosno ukupno (*nbytes*).

In [126]:
print(np_podaci.nbytes)
print(np_podaci.itemsize)
print(np_podaci.dtype)

print(tri_d.nbytes)
print(tri_d.itemsize)
print(tri_d.dtype)

36
4
int32
144
4
int32


Vidimo da oba *Array* objekta imaju isti tip (*int64*). To možemo definirati tijekom kreiranja *Array* objekta tako da metodi *array* proslijedimo argument *dtype* s nazivom tipa podataka. Probajmo umjesto cijelih brojeva koristiti decimalne.

In [127]:
tri_d = np.array(tri_d, dtype=np.float64)
tri_d

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]],

       [[25., 26., 27., 28.],
        [29., 30., 31., 32.],
        [33., 34., 35., 36.]]])

Provjerimo sada tip i količinu memorije za *Array tri_d*.

In [128]:
print(tri_d.nbytes)
print(tri_d.itemsize)
print(tri_d.dtype)

288
8
float64


Tip je sada drugačiji, a količina memorije je ostala ista jer *int64* i *float64* zauzimaju isto memorije (*8 byte*).

### Reshape

*Reshape* je metoda pomoću koje možemo promijeniti oblik, odnosno *shape* našeg *Array* objekta. Pokažimo to na primjeru. *Reshape* metoda prima *tuple* kao argument, ali umnožak njegovih elemenata mora biti isti kao i umnožak inicijalnih vrijednosti *Array* objekta. To znači da smo mi imali *tuple* (3, 3, 4) kao rezultat, a umnožak tih brojeva je 36. To znači da umnožak elemenata novog oblika mora biti 36. Recimo, (9, 4).

In [129]:
print('Shape tri_d:\t', tri_d.shape)
print('\nIzgled tri_d Array objekta PRIJE reshape():\n', tri_d)
# Rezultat 
# Shape tri_d:	 (3, 3, 4)

# Promjena 'oblika'
tri_d = tri_d.reshape(9, 4)
print('Shape tri_d nakon reshape():\t', tri_d.shape)
print('\nIzgled tri_d Array objekta nakon reshape():\n', tri_d)

Shape tri_d:	 (3, 3, 4)

Izgled tri_d Array objekta PRIJE reshape():
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]
  [21. 22. 23. 24.]]

 [[25. 26. 27. 28.]
  [29. 30. 31. 32.]
  [33. 34. 35. 36.]]]
Shape tri_d nakon reshape():	 (9, 4)

Izgled tri_d Array objekta nakon reshape():
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]
 [21. 22. 23. 24.]
 [25. 26. 27. 28.]
 [29. 30. 31. 32.]
 [33. 34. 35. 36.]]


Izgubili smo jednu dimenziju. Svedimo *tri_d Array* na samo jednu dimenziju.

In [130]:
# Promjena 'oblika'
tri_d = tri_d.reshape(36)
print('Shape tri_d nakon reshape():\t', tri_d.shape)
print('\nIzgled tri_d Array objekta nakon reshape():\n', tri_d)

Shape tri_d nakon reshape():	 (36,)

Izgled tri_d Array objekta nakon reshape():
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.]


Dakle, lista je jednodimenzionalni niz.

### Korisne funkcije u NumPy biblioteci

Do sada smo vidjeli kako NumPy *ndarray* možemo kreirati iz neke Python liste ili izravno pomoću *ndarray()* metode. Međutim, NumPy nudi nekoliko načina za kreiranje *Array* objekata od nasumično kreiranih objekata koje možemo koristiti u našim matematičkim analizama.

Krenimo s generatorom *Arraya* objekta u kojem su sve nule, tako što ćemo koristiti metodu *zeros()*, kojoj ćemo kao argument predati *tuple* s definiranim oblikom (*shape*) željenog *Array* objekta.

In [131]:
nule = np.zeros((3, 3, 3))
nule

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

Ako imamo metodu *zeros()*, moguće je da postoji identična metoda za jedinice naziva *ones()*. Provjerimo, ali pokušajmo promijeniti tip podatka u cijele brojeve (*dtype*).

In [132]:
jedinice = np.ones((3, 2, 5), dtype=np.int64)
jedinice

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int64)

Odlično. Ipak, bilo bi daleko korisnije kada bismo mogli imati *Array* s predefiniranom vrijednošću, kao recimo 3.14. Već smo vidjeli da *Array* objekt možemo množiti pa pokušajmo to iskoristiti.

In [133]:
pi = 3.14 * jedinice
pi

array([[[3.14, 3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14, 3.14]]])

Dakle, morali smo prvo kreirati *Array* željenog oblika s jedinicama i onda ga pomnožiti sa željenom vrijednošću. Postoji  brži i učinkovitiji način. Metoda *full()* koja prima dva argumenta, jedan tuple s oblikom *Arraay* objekta, a drugi s brojem koji želimo imati u našem *Array* objektu.

In [134]:
array_sedmca = np.full((3, 2, 5), 7)
array_sedmca

array([[[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]]])

Ponekad želimo imati *Array* u kojem su elementi poredani u sekvencu. Sjećate li se metode *range(start, stop, korak)*? NumPy radi s nizovima (*Arrays*) pa bi onda umjesto *array_range* trebala biti metoda naziva *arange*. Ostalo bi trebalo biti isto. Provjerimo.

In [135]:
np.arange(5, 15, 3)

array([ 5,  8, 11, 14])

Pomoću *arange()* metode generiramo jednodimenzionalni niz koji ima definiranu početnu vrijednost, krajnju (koja nije uključena) i korak između njih. NumPy nam omogućava kreiranje *Array* objekta koji ima početnu i krajnju vrijednost te broj elemenata između njih. Ova metoda zove se *linspace()*. Isprobajmo ju.

In [136]:
np.linspace(5, 15, 3)

array([ 5., 10., 15.])

In [137]:
np.linspace(5, 15, 5)

array([ 5. ,  7.5, 10. , 12.5, 15. ])

*arange* i *linspace* metode generiraju jednodimenzionalno polje.

2. Vježba
Generirajte nekoliko novih *Array* objekata pomoću *arange* i *linspace* metoda (neka ih bude minimalno 4) te im promijenite oblik po izboru.

In [138]:
# TODO

NumPy ima i generator slučajnih brojeva unutar normalne distribucije (nula je sredina svih generiranih brojeva na ovaj način - brojevi se generiraju u pozitivnom i negativnom smjeru). Iskoristimo ga.

In [139]:
niz_brojeva = np.random.randn(4, 5) # Dimenzije su zadane kao argument
niz_brojeva

array([[-0.64354933,  0.3266804 ,  1.03108742,  1.71230492,  1.88111702],
       [-0.34061865,  0.84146564,  0.21470983, -0.2146845 , -0.31439105],
       [ 0.0550391 , -2.12848932,  0.12650835,  0.89881965, -1.49830386],
       [ 0.82309661,  0.58433903, -0.43282537,  0.07137965, -0.52992143]])

### Slice notacija

Ako smo do sada mogli koristiti neke metode i funkcije vezane uz Python liste, provjerite možete li koristiti slice notaciju nad NumPy *Array* objektom. Podsjetnik: lista\[prvi_element : zadnji_element : korak\]. Sjetite se što znači negativni predznak za korak ili ako izostavite jedan od elemenata kao npr \[ : : \].

Kada radimo s višedimenzionalnim nizovima i ako koristimo *slice* notaciju, onda trebamo navesti i os na koju želimo primijeniti notaciju. Probajmo to napraviti s našim *tri_d Array* objektom.

In [140]:
tri_d = tri_d.reshape(6, 6)
tri_d = np.array(tri_d, dtype=np.int64) # promijenimo tip u cijele brojeve
tri_d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]], dtype=int64)

Pokušajmo dohvatiti sve elemente od početnog, do elementa s indeksom 4 (nije uključen).

In [141]:
tri_d[ : 4]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]], dtype=int64)

Kao rezultat smo dobili prva četiri reda. Dakle, redove s indeksima 0, 1, 2 i 3. Što ako želimo dohvatiti prva četiri elementa drugog reda? Ako ponovimo gornju naredbu, onda ćemo dobiti sve iz prva četiri reda, a mi želimo samo neke elemente iz drugog reda.

NumPy ima rješenje i za to. U *slice* notaciji ćemo dodati još jedan argument na prvo mjesto koji će odrediti o kojem redu se radi, a nakon tog argumenta ćemo navesti koje elemente tog reda želimo.

In [142]:
tri_d[1, : 4] # broj jedan označava indeks reda, a svi indeksi počinju od 0

array([ 7,  8,  9, 10], dtype=int64)

Pokušajmo onda iskoristiti ovu notaciju da dohvatimo zadnja 4 elementa predzadnjeg reda.

In [143]:
tri_d[-2, -4 : ]

array([27, 28, 29, 30], dtype=int64)

Vidjeli smo da je rad s redovima predefiniran. To znači kako nismo morali definirati o kojem se redu radi, nego je NumPy sam pretpostavio da želimo dohvatiti podatke iz redova. Međutim, što ako želimo dohvatiti podatke iz stupaca? Recimo, koji su podaci u drugom stupcu *tri_d* niza?

Odgovor na ovo pitanje je jako sličan odgovoru za redove, samo što argument koji navodimo za broj stupca, navodimo poslije *slice* notacije. Pokažimo na primjeru pa će biti jasnije:

In [144]:
tri_d[ : , 1]

array([ 2,  8, 14, 20, 26, 32], dtype=int64)

Koja je vrijednost u zadnja četiri elementa četvrtog stupca?

In [145]:
tri_d[ -4 : , 3]

array([16, 22, 28, 34], dtype=int64)

Dakle, *slice* notacija vrijedi i za NumPy nizove. Jednodimenzionalni nizovi su u stvari liste, kao što smo to naučili ranije, a ako želimo raditi s dvodimenzionalnim nizovima, onda slice notacija ima dodatne argumente. Prvi argument je indeks reda, nakon kojeg filtriramo pomoću *slice* notacije željene elemente. Ako želimo raditi sa stupcima, onda prvo navodimo *slice* notacijom filter elemenata, a nakon toga argument s indeksom stupca. Argumenti se, kao i kod funkcija, odvajaju zarezom.

Što ako želimo dohvatiti više redaka ili više stupaca? Ovdje ćemo morati koristiti dvostruku *slice* notaciju, odnosno kao da imamo dva argumenta. Prvi argument je zapisan u *slice* notaciji i odnosi se na redove, a drugi, također zapisan u *slice* notaciji, odnosi se na stupce. Zamislite kao da smo mišem selektirali dio tabele u Excel tabeli. Najbolje da to pokažemo na primjeru, u kojem ćemo dohvatiti prva četiri reda i zadnja četiri elementa tih prvih četiriju elementa.

In [146]:
# prisjetimo se kako izgleda tri_d niz
tri_d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]], dtype=int64)

In [147]:
tri_d[ : 4, -4: ]

array([[ 3,  4,  5,  6],
       [ 9, 10, 11, 12],
       [15, 16, 17, 18],
       [21, 22, 23, 24]], dtype=int64)

2. Vježba

Dohvatite prva dva stupca i svaki drugi red.

In [148]:
# TODO

### Kreiranje niza pomoću funkcije

Prije nego krenemo dalje s jednostavnijim matematičkim operacijama, upoznajmo se s još jednom opcijom za kreiranje nizova. Niz možemo kreirati pomoću rezultata neke funkcije. Ovo nam može biti jako korisno.

Na primjer: imamo dva broja koje želimo transformirati tako da drugi broj pomnožimo s brojem 15 i to dodamo prvom broju. Rezultat ove funkcije ćemo iskoristiti kao ulazni parametar za kreiranje niza. Za to će nam koristiti metoda *fromfunction* koja kao prvi argument prima funkciju (dakle, koristimo *lambda* funkcije), drugi element je oblik, odnosno *tuple* s podacima za *shape* niza i treći opcionalni argument je tip podatka. Pokažimo na primjeru.

In [149]:
def funkcija(x, y):
    return 15 * y + x

# Kojeg je tipa prvi argument? 
niz_funkcija = np.fromfunction(funkcija, (5, 8), dtype=np.int64)
niz_funkcija

array([[  0,  15,  30,  45,  60,  75,  90, 105],
       [  1,  16,  31,  46,  61,  76,  91, 106],
       [  2,  17,  32,  47,  62,  77,  92, 107],
       [  3,  18,  33,  48,  63,  78,  93, 108],
       [  4,  19,  34,  49,  64,  79,  94, 109]], dtype=int64)

3. Vježba

Implementirajte `linespace` i `zeros` pomoću `fromfunction`.

In [150]:
# TODO

4. Vježba Prikažite tablicu množenja do 12 pomoću NumPy niza i funkcije.**

In [151]:
funkcija = lambda x, y: x-x # TODO Kojeg su tipa argumenti?
tablica_mnozenja = np.fromfunction(funkcija, (13, 13), dtype=np.int64)

# Izbacimo elemente s vrijednostima 0
tablica_mnozenja[ 1 : , 1 : ]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

## Kopiranje cijelog ili dijela niza

Sada smo naučili kako izdvojiti dio niza iz veće cjeline. Ako taj dio pohranimo u neku varijablu i dalje ćemo imati **referencu** na originalne podatke. Pokažimo to na primjeru tablice množenja:

In [152]:
tablica_mnozenja_do100 = tablica_mnozenja[ 1:11, 1:11 ]
print('Tablica mnozenja\n', tablica_mnozenja)
print('Tablica mnozenja do 100\n', tablica_mnozenja_do100)

# Dodijeli vrijednost za ove elemente
tablica_mnozenja_do100[ 4:6, 4:6] = 9999
print('Tablica mnozenja\n', tablica_mnozenja)
print('Tablica mnozenja do 100\n', tablica_mnozenja_do100)

Tablica mnozenja
 [[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]
Tablica mnozenja do 100
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Tablica mnozenja
 [[   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0  

Kao što vidimo, promijenili smo **originalni skup podataka**. To treba izbjegavati, treba raditi na kopiji podataka. Za to imamo metodu *copy()*. Iskoristimo to na istom primjeru tablice množenja:

In [153]:
tablica_mnozenja_do50 = tablica_mnozenja[ 1:6, 1:11 ].copy()
# Ovo je ekvivalent
# tablica_mnozenja_do50 = np.copy(tablica_mnozenja[ 1:6, 1: ])

print('Tablica mnozenja\n', tablica_mnozenja)
print('Tablica mnozenja do 50\n', tablica_mnozenja_do50)

# Dodijeli vrijednost za ove elemente
tablica_mnozenja_do50[ -1:, 4:6] = 0
print('Tablica mnozenja\n', tablica_mnozenja)
print('Tablica mnozenja do 50\n', tablica_mnozenja_do50)

Tablica mnozenja
 [[   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0 9999 9999    0    0    0    0    0    0]
 [   0    0    0    0    0 9999 9999    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]]
Tablica mnozenja do 50
 [[   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    

### Povezivanje nizova

Osim što niz možemo kopirati pa tako kreirati novi niz, novi niz možemo kreirati i spajanjem dvaju ili više nizova u jedan pomoću *concatenate, vstack* i *hstack* metoda. Pokažimo to na primjeru.

In [154]:
niz1 = np.array([[1, 2, 3], [4, 5, 6]])
print(niz1)
print()
niz2 = np.array([[7, 8, 9], [10, 11, 12]])
print(niz2)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]


In [155]:
np.concatenate([niz1, niz2], axis=0) # Os 0 = Y - stupci/vertikalni smjer, os 1 = X - redovi/horizontalni smjer

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [156]:
np.concatenate([niz1, niz2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Možemo umjesto definiranja osi (*axis argument*) koristiti *vstack* (vertikalni smjer) ili *hstack* (horizontalni smjer)

In [157]:
np.vstack((niz1, niz2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [158]:
np.hstack((niz1, niz2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### Razdvajanje nizova

Znamo kako izdvojiti dio niza u jednu novu zasebnu cjelinu, ali ponekad imamo potrebu niz podijeliti na više cjelina, odnosno nizova po nekom kriteriju. Za to koristimo metode *split, hsplit* i *vsplit*. Pokažimo na primjerima kako se koriste ove metode.

In [159]:
niz = np.arange(1, 17).reshape(4, 4)
niz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [160]:
np.hsplit(niz, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [161]:
np.vsplit(niz, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

Kao argument, na koliko dijelova možemo proslijediti jednodimenzionalni niz pa ćemo prvotni niz podijeliti na više različitih dijelova. Recimo, prvo ćemo izdvojiti prva tri stupca, zatim preostale elemente u novi niz sve do 6. stupca. Kako nemamo toliko, dobit ćemo i jedan prazan niz.

In [162]:
np.hsplit(niz, np.array([3, 6]))

[array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]]),
 array([], shape=(4, 0), dtype=int32)]

Ako svaki novi dio pohranimo u neku novu varijablu, dobit ćemo nove *poglede* na originalni niz (sjetite se, nema kopiranja, nego i dalje zadržavamo reference pa ovo možemo smatrati kao pogled / *view* na taj dio niza.).

## Matematičke operacije s nizovima

NumPy je nastao kako bismo brzo i jednostavno izvršavali kompleksne matematičke operacije nad velikom količinom podatka. Da bismo došli do kompleksnih matematičkih operacija, krenut ćemo s jednostavnijim kao što su osnovne matematičke operacije:
- zbrajanje i oduzimanje
- množenje i dijeljenje
- potencije.

In [165]:
niz_a = np.arange(1, 65).reshape(8, 8)
niz_b = np.arange(101, 165).reshape(8, 8)

niz_a + niz_b

array([[102, 104, 106, 108, 110, 112, 114, 116],
       [118, 120, 122, 124, 126, 128, 130, 132],
       [134, 136, 138, 140, 142, 144, 146, 148],
       [150, 152, 154, 156, 158, 160, 162, 164],
       [166, 168, 170, 172, 174, 176, 178, 180],
       [182, 184, 186, 188, 190, 192, 194, 196],
       [198, 200, 202, 204, 206, 208, 210, 212],
       [214, 216, 218, 220, 222, 224, 226, 228]])

Ili pomoću funkcije metode *add()*:

In [166]:
np.add(niz_a, niz_b)

array([[102, 104, 106, 108, 110, 112, 114, 116],
       [118, 120, 122, 124, 126, 128, 130, 132],
       [134, 136, 138, 140, 142, 144, 146, 148],
       [150, 152, 154, 156, 158, 160, 162, 164],
       [166, 168, 170, 172, 174, 176, 178, 180],
       [182, 184, 186, 188, 190, 192, 194, 196],
       [198, 200, 202, 204, 206, 208, 210, 212],
       [214, 216, 218, 220, 222, 224, 226, 228]])

Analogno prethodnom primjeru, oduzimanje bi bilo pomoću znaka - ili metode *subtract()*.

In [167]:
niz_b - niz_a

array([[100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100]])

In [168]:
np.subtract(niz_b, niz_a)

array([[100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100]])

**PITANJE
Zbog čega smo kao rezultat oduzimanja dobili sve iste brojeve?**

Odgovor: zato jer je razlika elemenata po pozicijama uvijek identična. Da smo kreirali drugačije nizove, razlika bi bila drugačija.

5. Vježba
Primjere za množenje i dijeljenje napraviti sami.
**Pomoć: koristite engleske nazive za množenje i dijeljenje, odnosno *multiply* i *divide.***

In [ ]:
# TODO

### Ugrađene matematičke funkcije u NumPy biblioteci

NumPy ima jako puno ugrađenih funkcija. Da nabrojimo samo neke:
- trigonometrijske funkcije: *sin(), cos()* i *tan()*
- funkcije za korjenovanje *sqrt()* te *exp()* funkciju za računanje potencija nekog broja
- *log(), log2()* i *log10()* za računanje logaritama s bazom *e*, 2 ili 10
- *round()* za zaokruživanje na određeni broj decimalnih mjesta.

**Generirajte niz s nasumičnim brojevima proizvoljnog oblika (minimalno 4,4) te nad tim nizom provjerite kako rade navedene funkcije.**

### Statističke operacije u NumPy biblioteci
- *np.mean* - prosjek svih vrijednosti u nizu
- *np.std* - standardna devijacija
- *np.sum* - suma svih elemenata, metoda koristi argument *axis*
- *np.prod* - produkt svih elemenata
- *np.min, np.max* - minimalna/maksimalna vrijednost u nizu
- *np.argmin, np.argmax* - indeks elementa koji ima minimalnu/maksimalnu vrijednost
- *np.all* - vraća True ako su svi elementi nonzero (elementi koji imaju vrijednost nula ili nemaju definiranu vrijednost)
- *np.any* - vraća True ako je bilo koji element *nonzero*

6. Vježba

Generirajmo niz nasumičnih brojeva i provjerimo neke od gore navedenih statističkih operacija.

In [179]:
# TODO

### Funkcije filtriranja

NumPy ima ugrađenih nekoliko funkcija za filtriranje i obradu vrijednosti elementa u nizovima.
Prva s kojom ćemo se upoznati je *where()*. Ova funkcija prima prvi argument kao uvjet za filtriranje, a druga dva su operacije nad vrijednostima elemenata niza. Ako je rezultat uvjeta iz prvog argumenta točan, onda se primjenjuje drugi argument, a ako nije točan, onda se primjenjuje treći argument.

Generirajmo niz od 9 elemenata od -4 do +4 i svaki element koji je manji od nula podignimo na kvadrat, a ako je veći od nula, podignimo na treću potenciju.

In [170]:
niz = np.linspace(-4, 4, 9)
print(niz, '\n ')

np.where(niz < 0, niz**2, niz**3)

[-4. -3. -2. -1.  0.  1.  2.  3.  4.] 
 


array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

Druga jako slična funkcija je *select()*. Ova funkcija prima listu uvjeta kao prvi argument i listu operacija nad elementima koji zadovoljavaju uvjete iz liste. Nad prethodno kreiranim nizom, pronađimo elemente koji su:
- manji od -1 i ako ih pronađemo podignimo ih na kvadrat
- manji od 2 i ako ih pronađemo podignimo ih na treću potenciju
- veći i jednaki od 2 te ako ih pronađemo podignimo ih na četvrtu potenciju.

In [171]:
x = niz
np.select([x < -1, x < 2, x >= 2], [x**2, x**3, x**4])


array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

**np.unique** je funkcija koja vraća **jedinstvene** elemente niza

In [172]:
niz = np.random.randint(5, size=20)
print('niz\n', niz, '\n ')

print('Jedinstveni elementi niza\n', np.unique(niz))

niz
 [0 0 4 1 3 2 0 4 2 4 0 2 3 0 1 3 3 1 3 3] 
 
Jedinstveni elementi niza
 [0 1 2 3 4]


Prije nego krenemo s naprednom primjenom NumPy biblioteke, upoznajmo se s još nekoliko funkcija vezanih uz nizove:
- *np.fliplr* - sortira redove obrnutim redoslijedom - *fliplr = Flip L(eft)R(ight)*
- *np.flipud* - sortira stupce obrnutim redoslijedom - *flipud = Flip U(p)D(own)*
- *np.sort* - sortira niz po zadanim osima
- *np.ndarray.sort* - sortira niz tako da ga modificira.

In [173]:
niz = np.arange(1, 65).reshape(8, 8)
niz

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [174]:
np.fliplr(niz)

array([[ 8,  7,  6,  5,  4,  3,  2,  1],
       [16, 15, 14, 13, 12, 11, 10,  9],
       [24, 23, 22, 21, 20, 19, 18, 17],
       [32, 31, 30, 29, 28, 27, 26, 25],
       [40, 39, 38, 37, 36, 35, 34, 33],
       [48, 47, 46, 45, 44, 43, 42, 41],
       [56, 55, 54, 53, 52, 51, 50, 49],
       [64, 63, 62, 61, 60, 59, 58, 57]])

In [175]:
np.flipud(niz)

array([[57, 58, 59, 60, 61, 62, 63, 64],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [ 1,  2,  3,  4,  5,  6,  7,  8]])

In [187]:
np.sort(niz, axis=0)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [177]:
np.sort(niz, axis=1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])